### ISSUE TITLE
Better instructions for installing as an app.

### ISSUE THREAD

**Issue by ghost** [agiliq/Dinette#44]
I am hoping that I could get some detailed instructions for this app as just adding this app seems to not be liked. I am wondering if I have the incorrect version of MarkupField installed. 

root@foreignhost:/var/www/tavern# python manage.py migrate
/usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:6: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

/usr/local/lib/python2.7/dist-packages/django/contrib/sites/models.py:78: RemovedInDjango19Warning: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Site(models.Model):

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 312, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/**init**.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/var/www/tavern/dinette/models.py", line 14, in <module>
    from markupfield.fields import MarkupField
  File "/usr/local/lib/python2.7/dist-packages/markupfield/fields.py", line 8, in <module>
    from markupfield import markup
  File "/usr/local/lib/python2.7/dist-packages/markupfield/markup.py", line 58, in <module>
    extensions=[makeExtension(css_class='highlight')])
TypeError: makeExtension() got an unexpected keyword argument 'css_class'

**Comment by ghost** [comment]
oh and yes, I have 1.8
 python -c "import django; print(django.get_version())"
1.8

**Comment by BurkovBA** [comment]
Have the same problem on django 1.7.11 with django-markupfield-1.3.5.

**Comment by BurkovBA** [comment]
Sorted this out. Had an obsolete version of `python-markdown` package, installed from aptitude. Installed fresh one with pip and the problem's gone.
